### ISSUE TITLE
[Bug]: Discord detected in a web browser despite not being signed in Discord on it

### ISSUE THREAD

**Issue by Hurikejn** [Azn9/JetBrains-Discord-Integration#225] opened 2024-11-13 12:37 UTC
### What happened?

Hello, I am having an issue, where the plugin will say that Discord was detected on my browser, despite not even being signed in to Discord on it. I am using Brave. This issue does not happen on other PCs though.

![image](https://github.com/user-attachments/assets/a3f9b73d-ad9e-40c5-9835-1350c8f7cbc1)
![image](https://github.com/user-attachments/assets/f1536832-4e12-4e3c-9004-e47c5b1c0551)

### IDE version

21.0.4

### Plugin version

2.1.4

### What operating system are you using?

Windows

**Comment by Azn9** [comment] 2024-11-13 12:51
Hello, I'm aware of this, I need to fix it. TLDR, if the plugin don't detect a running client, it try to detect a browser *with discord open*. However, currently it only detects "a browser", not if there is discord or not :(

Duplicate of #218

**Closed as not planned by Azn9** 2024-11-13 12:51 UTC
Labels: bug
