### ISSUE TITLE
[Bug]: IDE internal error

### ISSUE THREAD

**Issue by maxoux53** [Azn9/JetBrains-Discord-Integration#88] opened 2024-02-29 11:49 UTC
### What happened?

![image](https://github.com/Azn9/JetBrains-Discord-Integration/assets/71935156/1a098a99-829f-46c6-9f05-9f877f5914a7)

### IDE version

CLion 2024.1 EAP (Nova) Build #CL-241.11109

### Plugin version

2.0.8

### What operating system are you using?

MacOS

### Relevant log output

```shell
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'dev.azn9.plugins.discord.actions.ApplicationShowAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: dev.azn9.plugins.discord]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:198)
```

**Comment by Azn9** [comment] 2024-02-29 14:35
Duplicate of #79

**Closed as not planned by Azn9** 2024-02-29 14:35 UTC
Labels: bug, duplicate
