### ISSUE TITLE
[Bug]: Error after installing plugin rider

### ISSUE THREAD

**Issue by adrianbodin** [Azn9/JetBrains-Discord-Integration#103] opened 2024-05-09 18:28 UTC
### What happened?

I just installed the plugin but get an error.

### IDE version

JetBrains Rider 2024.1.2

### Plugin version

2.0.8

### What operating system are you using?

Windows

### Relevant log output

```shell
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'dev.azn9.plugins.discord.actions.ApplicationShowAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: dev.azn9.plugins.discord]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:200)
```

**Comment by Azn9** [comment] 2024-05-09 19:19
Duplicate of #79 
Just to let you know, this issue is not preventing the plugin from working properly at the moment. Its fix has already been coded, but I didn't have enough time to finalize everything I wanted in the release. 
I am really busy with school atm, this week is my final week so I am completely focusing on my final project.
However, if everything goes well, this should be released by the end of May.

**Closed as not planned by Azn9** 2024-05-09 19:19 UTC
Labels: bug
